# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

steps:
  #######
  - label: ":golang: Build for {{ matrix.platform }} on {{ matrix.arch }}"
    key: build
    command: |
      docker run \
      -v $(pwd):/usr/src/plugin \
      -v $(pwd)/.build:/go \
      -w /usr/src/plugin \
      -e GOOS={{ matrix.platform }} \
      -e GOARCH={{ matrix.arch }} \
      golang:1.20 go build -buildvcs=false
    matrix:
      setup:
        platform:
          - darwin
        arch:
          - amd64
          - arm64
    artifact_paths:
      - "packer-plugin-hostmgr"

  - label: ":golang-lint: Lint"
    key: lint
    command: |
      rm -rf .git && make lint

  - label: ":ruby: Ruby Lint"
    key: lint-ruby
    command: make lint-ruby

  - label: ":github: Release Build"
    key: "gem-push"
    if: build.tag != null
    depends_on:
     - build
     - lint
     - lint-ruby
    command: |
      make package VERSION=${BUILDKITE_TAG}
      make publish VERSION=${BUILDKITE_TAG}
    artifact_paths:
      - "packer-plugin-hostmgr*"
